package fac

type General struct {
	AgenciesWithPriorFindings                  string `json:"agencies_with_prior_findings"`
	AuditPeriodCovered                         string `json:"audit_period_covered"`
	AuditType                                  string `json:"audit_type"`
	AuditYear                                  string `json:"audit_year"`
	AuditeeAddressLine1                        string `json:"auditee_address_line_1"`
	AuditeeCertifiedDate                       string `json:"auditee_certified_date"`
	AuditeeCertifyName                         string `json:"auditee_certify_name"`
	AuditeeCertifyTitle                        string `json:"auditee_certify_title"`
	AuditorCertifyName                         string `json:"auditor_certify_name"`
	AuditorCertifyTitle                        string `json:"auditor_certify_title"`
	AuditeeCity                                string `json:"auditee_city"`
	AuditeeContactName                         string `json:"auditee_contact_name"`
	AuditeeContactTitle                        string `json:"auditee_contact_title"`
	AuditeeEin                                 string `json:"auditee_ein"`
	AuditeeEmail                               string `json:"auditee_email"`
	AuditeeName                                string `json:"auditee_name"`
	AuditeePhone                               string `json:"auditee_phone"`
	AuditeeState                               string `json:"auditee_state"`
	AuditeeUei                                 string `json:"auditee_uei"`
	AuditeeZip                                 string `json:"auditee_zip"`
	AuditorAddressLine1                        string `json:"auditor_address_line_1"`
	AuditorCertifiedDate                       string `json:"auditor_certified_date"`
	AuditorCity                                string `json:"auditor_city"`
	AuditorContactName                         string `json:"auditor_contact_name"`
	AuditorContactTitle                        string `json:"auditor_contact_title"`
	AuditorCountry                             string `json:"auditor_country"`
	AuditorEin                                 string `json:"auditor_ein"`
	AuditorEmail                               string `json:"auditor_email"`
	AuditorFirmName                            string `json:"auditor_firm_name"`
	AuditorForeignAddress                      string `json:"auditor_foreign_address"`
	AuditorPhone                               string `json:"auditor_phone"`
	AuditorState                               string `json:"auditor_state"`
	AuditorZip                                 string `json:"auditor_zip"`
	CognizantAgency                            any    `json:"cognizant_agency"`
	DataSource                                 string `json:"data_source"`
	DateCreated                                string `json:"date_created"`
	DollarThreshold                            int    `json:"dollar_threshold"`
	EntityType                                 string `json:"entity_type"`
	FacAcceptedDate                            string `json:"fac_accepted_date"`
	FyEndDate                                  string `json:"fy_end_date"`
	FyStartDate                                string `json:"fy_start_date"`
	GaapResults                                string `json:"gaap_results"`
	IsAdditionalUeis                           string `json:"is_additional_ueis"`
	IsAicpaAuditGuideIncluded                  string `json:"is_aicpa_audit_guide_included"`
	IsGoingConcernIncluded                     string `json:"is_going_concern_included"`
	IsInternalControlDeficiencyDisclosed       string `json:"is_internal_control_deficiency_disclosed"`
	IsInternalControlMaterialWeaknessDisclosed string `json:"is_internal_control_material_weakness_disclosed"`
	IsLowRiskAuditee                           string `json:"is_low_risk_auditee"`
	IsMaterialNoncomplianceDisclosed           string `json:"is_material_noncompliance_disclosed"`
	IsMultipleEins                             string `json:"is_multiple_eins"`
	IsPublic                                   bool   `json:"is_public"`
	IsSecondaryAuditors                        string `json:"is_secondary_auditors"`
	IsSpFrameworkRequired                      string `json:"is_sp_framework_required"`
	NumberMonths                               string `json:"number_months"`
	OversightAgency                            string `json:"oversight_agency"`
	ReadyForCertificationDate                  string `json:"ready_for_certification_date"`
	ReportID                                   string `json:"report_id"`
	SpFrameworkBasis                           string `json:"sp_framework_basis"`
	SpFrameworkOpinions                        string `json:"sp_framework_opinions"`
	SubmittedDate                              string `json:"submitted_date"`
	TotalAmountExpended                        int    `json:"total_amount_expended"`
	TypeAuditCode                              string `json:"type_audit_code"`
}
