// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"database/sql"
	"time"
)

type FederalAward struct {
	ID                            int64
	RawID                         int64
	ReportID                      string
	AuditYear                     int64
	AdditionalAwardIdentification string
	AmountExpended                int64
	AwardReference                string
	ClusterName                   string
	ClusterTotal                  int64
	FederalAgencyPrefix           string
	FederalAwardExtension         string
	FederalProgramName            string
	FederalProgramTotal           int64
	FindingsCount                 interface{}
	IsDirect                      string
	IsLoan                        string
	IsMajor                       string
	IsPassthroughAward            string
	LoanBalance                   string
	AuditReportType               string
	OtherClusterName              string
	PassthroughAmount             interface{}
	StateClusterName              string
}

type Finding struct {
	ID                      int64
	RawID                   int64
	ReportID                string
	AuditYear               int64
	AwardReference          string
	ReferenceNumber         string
	IsMaterialWeakness      string
	IsModifiedOpinion       string
	IsOtherFindings         string
	IsOtherMatters          string
	IsQuestionedCosts       string
	IsRepeatFinding         string
	IsSignificantDeficiency string
	PriorFindingRefNumbers  string
	TypeRequirement         string
}

type General struct {
	ID                                         int64
	RawID                                      int64
	ReportID                                   string
	AuditeeCertifyName                         string
	AuditeeCertifyTitle                        string
	AuditeeContactName                         string
	AuditeeEmail                               string
	AuditeeName                                string
	AuditeePhone                               string
	AuditeeContactTitle                        string
	AuditeeAddressLine1                        string
	AuditeeCity                                string
	AuditeeState                               string
	AuditeeEin                                 string
	AuditeeUei                                 string
	IsAdditionalUeis                           string
	AuditeeZip                                 string
	AuditorPhone                               string
	AuditorState                               string
	AuditorCity                                string
	AuditorContactTitle                        string
	AuditorAddressLine1                        string
	AuditorZip                                 string
	AuditorCountry                             string
	AuditorContactName                         string
	AuditorEmail                               string
	AuditorFirmName                            string
	AuditorForeignAddress                      string
	AuditorEin                                 string
	CognizantAgency                            interface{}
	OversightAgency                            interface{}
	DateCreated                                time.Time
	ReadyForCertificationDate                  time.Time
	AuditorCertifiedDate                       time.Time
	AuditeeCertifiedDate                       time.Time
	SubmittedDate                              time.Time
	FyEndDate                                  time.Time
	FyStartDate                                time.Time
	AuditYear                                  string
	AuditType                                  string
	GaapResults                                string
	SpFrameworkBasis                           string
	IsSpFrameworkRequired                      string
	SpFrameworkOpinions                        string
	IsGoingConcernIncluded                     string
	IsInternalControlDeficiencyDisclosed       string
	IsInternalControlMaterialWeaknessDisclosed string
	IsMaterialNoncomplianceDisclosed           string
	IsAicpaAuditGuideIncluded                  string
	DollarThreshold                            int64
	IsLowRiskAuditee                           string
	AgenciesWithPriorFindings                  string
	EntityType                                 string
	NumberMonths                               string
	AuditPeriodCovered                         string
	TotalAmountExpended                        int64
	TypeAuditCode                              string
	IsPublic                                   bool
	DataSource                                 string
	FacAcceptedDate                            time.Time
	AuditorCertifyName                         string
	AuditorCertifyTitle                        string
}

type NotesToSefa struct {
	ID                   int64
	RawID                int64
	ReportID             string
	AuditYear            int64
	AccountingPolicies   string
	IsMinimisRateUsed    string
	RateExplained        string
	Content              string
	Title                string
	ContainsChartOrTable string
}

type Pdf struct {
	ID           int64
	RawID        sql.NullInt64
	IsDownloaded sql.NullBool
}

type Raw struct {
	ID        int64
	Source    string
	Json      string
	CreatedAt sql.NullTime
}
