// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"time"
)

type General struct {
	ID                                         int64
	ReportID                                   string
	AuditeeCertifyName                         string
	AuditeeCertifyTitle                        string
	AuditeeContactName                         string
	AuditeeEmail                               string
	AuditeeName                                string
	AuditeePhone                               string
	AuditeeContactTitle                        string
	AuditeeAddressLine1                        string
	AuditeeCity                                string
	AuditeeState                               string
	AuditeeEin                                 string
	AuditeeUei                                 string
	IsAdditionalUeis                           string
	AuditeeZip                                 string
	AuditorPhone                               string
	AuditorState                               string
	AuditorCity                                string
	AuditorContactTitle                        string
	AuditorAddressLine1                        string
	AuditorZip                                 string
	AuditorCountry                             string
	AuditorContactName                         string
	AuditorEmail                               string
	AuditorFirmName                            string
	AuditorForeignAddress                      string
	AuditorEin                                 string
	CognizantAgency                            interface{}
	OversightAgency                            interface{}
	DateCreated                                time.Time
	ReadyForCertificationDate                  time.Time
	AuditorCertifiedDate                       time.Time
	AuditeeCertifiedDate                       time.Time
	SubmittedDate                              time.Time
	FyEndDate                                  time.Time
	FyStartDate                                time.Time
	AuditYear                                  string
	AuditType                                  string
	GaapResults                                string
	SpFrameworkBasis                           string
	IsSpFrameworkRequired                      string
	SpFrameworkOpinions                        string
	IsGoingConcernIncluded                     string
	IsInternalControlDeficiencyDisclosed       string
	IsInternalControlMaterialWeaknessDisclosed string
	IsMaterialNoncomplianceDisclosed           string
	IsAicpaAuditGuideIncluded                  string
	DollarThreshold                            int64
	IsLowRiskAuditee                           string
	AgenciesWithPriorFindings                  string
	EntityType                                 string
	NumberMonths                               string
	AuditPeriodCovered                         string
	TotalAmountExpended                        int64
	TypeAuditCode                              string
	IsPublic                                   bool
	DataSource                                 string
	FacAcceptedDate                            time.Time
	AuditorCertifyName                         string
	AuditorCertifyTitle                        string
}

type Raw struct {
	ID     int64
	Source string
	Json   string
}
