CREATE TABLE IF NOT EXISTS raw (
  id INTEGER PRIMARY KEY,
  source TEXT NOT NULL,
  json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS general (
	id INTEGER PRIMARY KEY,
	report_id text NOT NULL,
	auditee_certify_name text NOT NULL,
	auditee_certify_title text NOT NULL,
	auditee_contact_name text NOT NULL,
	auditee_email text NOT NULL,
	auditee_name text NOT NULL,
	auditee_phone text NOT NULL,
	auditee_contact_title text NOT NULL,
	auditee_address_line_1 text NOT NULL,
	auditee_city text NOT NULL,
	auditee_state text NOT NULL,
	auditee_ein text NOT NULL,
	auditee_uei text NOT NULL,
	is_additional_ueis text NOT NULL,
	auditee_zip text NOT NULL,
	auditor_phone text NOT NULL,
	auditor_state text NOT NULL,
	auditor_city text NOT NULL,
	auditor_contact_title text NOT NULL,
	auditor_address_line_1 text NOT NULL,
	auditor_zip text NOT NULL,
	auditor_country text NOT NULL,
	auditor_contact_name text NOT NULL,
	auditor_email text NOT NULL,
	auditor_firm_name text NOT NULL,
	auditor_foreign_address text NOT NULL,
	auditor_ein text NOT NULL,
	cognizant_agency text NULL,
	oversight_agency text NULL,
	date_created date NOT NULL,
	ready_for_certification_date date NOT NULL,
	auditor_certified_date date NOT NULL,
	auditee_certified_date date NOT NULL,
	submitted_date date NOT NULL,
	fy_end_date date NOT NULL,
	fy_start_date date NOT NULL,
	audit_year text NOT NULL,
	audit_type text NOT NULL,
	gaap_results text NOT NULL,
	sp_framework_basis text NOT NULL,
	is_sp_framework_required text NOT NULL,
	sp_framework_opinions text NOT NULL,
	is_going_concern_included text NOT NULL,
	is_internal_control_deficiency_disclosed text NOT NULL,
	is_internal_control_material_weakness_disclosed text NOT NULL,
	is_material_noncompliance_disclosed text NOT NULL,
	is_aicpa_audit_guide_included text NOT NULL,
	dollar_threshold int8 NOT NULL,
	is_low_risk_auditee text NOT NULL,
	agencies_with_prior_findings text NOT NULL,
	entity_type text NOT NULL,
	number_months text NOT NULL,
	audit_period_covered text NOT NULL,
	total_amount_expended int8 NOT NULL,
	type_audit_code text NOT NULL,
	is_public bool NOT NULL,
	data_source text NOT NULL,
	fac_accepted_date date NOT NULL,
	auditor_certify_name text NOT NULL,
	auditor_certify_title text NOT NULL
);